#!/usr/bin/env bash
# SSH client configuration to use the private key ~/.ssh/holberton
# SSH client configuration to refuse to authenticate using a password

Host 54.172.211.21
     PasswordAuthentication no
     IdentityFile ~/.ssh/school
