#!/usr/bin/env bash
# same as task 1
lsof -t -i:8080 | xargs -r kill
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
