#!/usr/bin/env bash
# no comments

sudo apt update -y
sudo apt install nginx -y
sudo apt install haproxy -y

CONFIG="\
backend web-backend
	balance roundrobin
	server 1861-web-01 34.74.125.88:80 check
	server 1861-web-02 35.243.133.178:80 check

frontend main
	bind *:80
	mode http
	default_backend web-backend
"
sudo echo "$CONFIG" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
